CC=i586-mingw32msvc-gcc
CFLAGS=-Wall -g \
		 -D_WIN32_WINNT=0x0501 -DDEBUG
OBJS=	iobuf.o print.o msgparser.o nethelper.o netaddr.o

all: $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(OBJS) $(BIN)
